CREATE TABLE accesos
(
    id_usuario      INTEGER      NOT NULL,
    telefono_acceso VARCHAR(150) NOT NULL,
    correo_acceso   VARCHAR(150) NOT NULL,
    clave_acceso    VARCHAR(150) NOT NULL,
    uuid_acceso     VARCHAR(150) NOT NULL,
    CONSTRAINT pk_accesos PRIMARY KEY (id_usuario)
);

CREATE TABLE anuncios
(
    id_vacante             INTEGER      NOT NULL,
    nombre_publico_anuncio VARCHAR(200) NOT NULL,
    nombre_privado_anuncio VARCHAR(200) NOT NULL,
    tipo_anuncio           VARCHAR(50)  NOT NULL,
    tamanio_anuncio        VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_anuncios PRIMARY KEY (id_vacante)
);

CREATE TABLE archivos
(
    id_archivo             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_publico_archivo VARCHAR(200)                             NOT NULL,
    nombre_archivo_archivo VARCHAR(200)                             NOT NULL,
    tipo_archivo           VARCHAR(50)                              NOT NULL,
    tamanio_archivo        VARCHAR(50)                              NOT NULL,
    grupo_archivo          SMALLINT                                 NOT NULL,
    id_usuario             INTEGER                                  NOT NULL,
    CONSTRAINT pk_archivos PRIMARY KEY (id_archivo)
);

CREATE TABLE auditorias
(
    id_auditoria             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_entidad_auditoria VARCHAR(100)                             NOT NULL,
    id_referencia_auditoria  INTEGER                                  NOT NULL,
    fecha_auditoria          TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    tipo_cambio_auditoria    VARCHAR(200)                             NOT NULL,
    comentario_auditoria     TEXT                                     NOT NULL,
    id_usuario_auditoria     INTEGER                                  NOT NULL,
    CONSTRAINT pk_auditorias PRIMARY KEY (id_auditoria)
);

CREATE TABLE empresas
(
    id_empresa        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_empresa    VARCHAR(200)                             NOT NULL,
    direccion_empresa VARCHAR(200)                             NOT NULL,
    telefono_empresa  VARCHAR(200)                             NOT NULL,
    id_tipo_empresa   INTEGER                                  NOT NULL,
    CONSTRAINT pk_empresas PRIMARY KEY (id_empresa)
);

CREATE TABLE estados_postulaciones
(
    id_estado_postulacion     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_estado_postulacion VARCHAR(150)                             NOT NULL,
    orden_estado_postulacion  SMALLINT                                 NOT NULL,
    CONSTRAINT pk_estados_postulaciones PRIMARY KEY (id_estado_postulacion)
);

CREATE TABLE estados_vacantes
(
    id_estado_vacante     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_estado_vacante VARCHAR(100)                             NOT NULL,
    orden_estado_vacante  SMALLINT                                 NOT NULL,
    CONSTRAINT pk_estados_vacantes PRIMARY KEY (id_estado_vacante)
);

CREATE TABLE historial_estados_postulaciones
(
    id_historial_postulacion      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_historial_postulacion   TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    detalle_historial_postulacion TEXT                                     NOT NULL,
    id_postulacion                INTEGER                                  NOT NULL,
    id_estado_postulacion         INTEGER                                  NOT NULL,
    CONSTRAINT pk_historial_estados_postulaciones PRIMARY KEY (id_historial_postulacion)
);

CREATE TABLE historial_estados_vacantes
(
    id_historial_estado_vacante    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_historial_estado_vacante TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    id_vacante                     INTEGER                                  NOT NULL,
    id_estado_vacante              INTEGER                                  NOT NULL,
    CONSTRAINT pk_historial_estados_vacantes PRIMARY KEY (id_historial_estado_vacante)
);

CREATE TABLE imagenes
(
    id_imagen             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_publico_imagen VARCHAR(200)                             NOT NULL,
    nombre_privado_imagen VARCHAR(200)                             NOT NULL,
    tipo_imagen           VARCHAR(50)                              NOT NULL,
    tamanio_imagen        VARCHAR(50)                              NOT NULL,
    favorita_imagen       SMALLINT                                 NOT NULL,
    id_usuario            INTEGER                                  NOT NULL,
    CONSTRAINT pk_imagenes PRIMARY KEY (id_imagen)
);

CREATE TABLE ingresos
(
    id_ingreso    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_ingreso TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    id_usuario    INTEGER                                  NOT NULL,
    CONSTRAINT pk_ingresos PRIMARY KEY (id_ingreso)
);

CREATE TABLE intereses
(
    id_empresa   INTEGER  NOT NULL,
    id_usuario   INTEGER  NOT NULL,
    tipo_interes SMALLINT NOT NULL,
    CONSTRAINT pk_intereses PRIMARY KEY (id_empresa, id_usuario)
);

CREATE TABLE mensajes
(
    id_mensaje          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto_mensaje       TEXT                                     NOT NULL,
    fecha_mensaje       TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    estado_mensaje      SMALLINT                                 NOT NULL,
    id_postulacion      INTEGER                                  NOT NULL,
    id_usuario_responde INTEGER                                  NOT NULL,
    CONSTRAINT pk_mensajes PRIMARY KEY (id_mensaje)
);

CREATE TABLE palabras_claves
(
    id_palabra_clave    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto_palabra_clave VARCHAR(150)                             NOT NULL,
    CONSTRAINT pk_palabras_claves PRIMARY KEY (id_palabra_clave)
);

CREATE TABLE postulaciones
(
    id_postulacion              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_postulacion           TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    correspondencia_postulacion SMALLINT                                 NOT NULL,
    estado_postulacion          SMALLINT                                 NOT NULL,
    id_vacante                  INTEGER                                  NOT NULL,
    id_usuario                  INTEGER                                  NOT NULL,
    CONSTRAINT pk_postulaciones PRIMARY KEY (id_postulacion)
);

CREATE TABLE rel_usuario_palabraclave
(
    id_usuario       INTEGER NOT NULL,
    id_palabra_clave INTEGER NOT NULL,
    CONSTRAINT pk_rel_usuario_palabraclave PRIMARY KEY (id_usuario, id_palabra_clave)
);

CREATE TABLE rel_usuarios_empresas
(
    id_usuario                  INTEGER  NOT NULL,
    id_empresa                  INTEGER  NOT NULL,
    permiso_rel_usuario_empresa SMALLINT NOT NULL,
    CONSTRAINT pk_rel_usuarios_empresas PRIMARY KEY (id_usuario, id_empresa)
);

CREATE TABLE rel_vacante_palabraclave
(
    id_vacante       INTEGER NOT NULL,
    id_palabra_clave INTEGER NOT NULL,
    CONSTRAINT pk_rel_vacante_palabraclave PRIMARY KEY (id_vacante, id_palabra_clave)
);

CREATE TABLE requisitos
(
    id_requisito      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo_requisito  VARCHAR(200)                             NOT NULL,
    detalle_requisito TEXT                                     NOT NULL,
    orden_requisito   SMALLINT                                 NOT NULL,
    id_vacante        INTEGER                                  NOT NULL,
    CONSTRAINT pk_requisitos PRIMARY KEY (id_requisito)
);

CREATE TABLE roles
(
    id_rol     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_rol VARCHAR(150)                             NOT NULL,
    estado_rol SMALLINT                                 NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id_rol)
);

CREATE TABLE tipo_empresas
(
    id_tipo_empresa     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_tipo_empresa VARCHAR(150)                             NOT NULL,
    estado_tipo_empresa SMALLINT                                 NOT NULL,
    CONSTRAINT pk_tipo_empresas PRIMARY KEY (id_tipo_empresa)
);

CREATE TABLE ubicaciones
(
    id_ubicacion       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_ubicacion   VARCHAR(150)                             NOT NULL,
    id_dane_ubicacion  VARCHAR(30)                              NOT NULL,
    longitud_ubicacion VARCHAR(30)                              NOT NULL,
    latitud_ubicacion  VARCHAR(30)                              NOT NULL,
    id_padre_ubicacion INTEGER,
    CONSTRAINT pk_ubicaciones PRIMARY KEY (id_ubicacion)
);

CREATE TABLE usuarios
(
    id_usuario             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_documento_usuario SMALLINT                                 NOT NULL,
    documento_usuario      VARCHAR(150)                             NOT NULL,
    nombres_usuario        VARCHAR(50)                              NOT NULL,
    apellidos_usuario      VARCHAR(50)                              NOT NULL,
    estado_usuario         SMALLINT                                 NOT NULL,
    id_ubicacion           INTEGER                                  NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario)
);

CREATE TABLE usuarios_roles
(
    id_usuario INTEGER NOT NULL,
    id_rol     INTEGER NOT NULL,
    CONSTRAINT pk_usuarios_roles PRIMARY KEY (id_usuario, id_rol)
);

CREATE TABLE vacantes
(
    id_vacante           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo_vacante       VARCHAR(300)                             NOT NULL,
    detalle_vacante      TEXT                                     NOT NULL,
    fecha_inicio_vacante TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    fecha_fin_vacante    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    estado_vacante       SMALLINT                                 NOT NULL,
    id_ubicacion         INTEGER                                  NOT NULL,
    id_empresa           INTEGER                                  NOT NULL,
    id_usuario           INTEGER                                  NOT NULL,
    CONSTRAINT pk_vacantes PRIMARY KEY (id_vacante)
);

ALTER TABLE accesos
    ADD CONSTRAINT uc_accesos_correo_acceso UNIQUE (correo_acceso);

ALTER TABLE palabras_claves
    ADD CONSTRAINT uc_palabras_claves_texto_palabra_clave UNIQUE (texto_palabra_clave);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_nombre_rol UNIQUE (nombre_rol);

ALTER TABLE tipo_empresas
    ADD CONSTRAINT uc_tipo_empresas_nombre_tipo_empresa UNIQUE (nombre_tipo_empresa);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_documento_usuario UNIQUE (documento_usuario);

ALTER TABLE accesos
    ADD CONSTRAINT FK_ACCESOS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE anuncios
    ADD CONSTRAINT FK_ANUNCIOS_ON_ID_VACANTE FOREIGN KEY (id_vacante) REFERENCES vacantes (id_vacante);

ALTER TABLE archivos
    ADD CONSTRAINT FK_ARCHIVOS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE auditorias
    ADD CONSTRAINT FK_AUDITORIAS_ON_ID_USUARIO_AUDITORIA FOREIGN KEY (id_usuario_auditoria) REFERENCES usuarios (id_usuario);

ALTER TABLE empresas
    ADD CONSTRAINT FK_EMPRESAS_ON_ID_TIPO_EMPRESA FOREIGN KEY (id_tipo_empresa) REFERENCES tipo_empresas (id_tipo_empresa);

ALTER TABLE historial_estados_postulaciones
    ADD CONSTRAINT FK_HISTORIAL_ESTADOS_POSTULACIONES_ON_ID_ESTADO_POSTULACION FOREIGN KEY (id_estado_postulacion) REFERENCES estados_postulaciones (id_estado_postulacion);

ALTER TABLE historial_estados_postulaciones
    ADD CONSTRAINT FK_HISTORIAL_ESTADOS_POSTULACIONES_ON_ID_POSTULACION FOREIGN KEY (id_postulacion) REFERENCES postulaciones (id_postulacion);

ALTER TABLE historial_estados_vacantes
    ADD CONSTRAINT FK_HISTORIAL_ESTADOS_VACANTES_ON_ID_ESTADO_VACANTE FOREIGN KEY (id_estado_vacante) REFERENCES estados_vacantes (id_estado_vacante);

ALTER TABLE historial_estados_vacantes
    ADD CONSTRAINT FK_HISTORIAL_ESTADOS_VACANTES_ON_ID_VACANTE FOREIGN KEY (id_vacante) REFERENCES vacantes (id_vacante);

ALTER TABLE imagenes
    ADD CONSTRAINT FK_IMAGENES_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE ingresos
    ADD CONSTRAINT FK_INGRESOS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES accesos (id_usuario);

ALTER TABLE intereses
    ADD CONSTRAINT FK_INTERESES_ON_ID_EMPRESA FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa);

ALTER TABLE intereses
    ADD CONSTRAINT FK_INTERESES_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE mensajes
    ADD CONSTRAINT FK_MENSAJES_ON_ID_POSTULACION FOREIGN KEY (id_postulacion) REFERENCES postulaciones (id_postulacion);

ALTER TABLE mensajes
    ADD CONSTRAINT FK_MENSAJES_ON_ID_USUARIO_RESPONDE FOREIGN KEY (id_usuario_responde) REFERENCES usuarios (id_usuario);

ALTER TABLE postulaciones
    ADD CONSTRAINT FK_POSTULACIONES_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE postulaciones
    ADD CONSTRAINT FK_POSTULACIONES_ON_ID_VACANTE FOREIGN KEY (id_vacante) REFERENCES vacantes (id_vacante);

ALTER TABLE rel_usuarios_empresas
    ADD CONSTRAINT FK_REL_USUARIOS_EMPRESAS_ON_ID_EMPRESA FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa);

ALTER TABLE rel_usuarios_empresas
    ADD CONSTRAINT FK_REL_USUARIOS_EMPRESAS_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE rel_usuario_palabraclave
    ADD CONSTRAINT FK_REL_USUARIO_PALABRACLAVE_ON_ID_PALABRA_CLAVE FOREIGN KEY (id_palabra_clave) REFERENCES palabras_claves (id_palabra_clave);

ALTER TABLE rel_usuario_palabraclave
    ADD CONSTRAINT FK_REL_USUARIO_PALABRACLAVE_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE rel_vacante_palabraclave
    ADD CONSTRAINT FK_REL_VACANTE_PALABRACLAVE_ON_ID_PALABRA_CLAVE FOREIGN KEY (id_palabra_clave) REFERENCES palabras_claves (id_palabra_clave);

ALTER TABLE rel_vacante_palabraclave
    ADD CONSTRAINT FK_REL_VACANTE_PALABRACLAVE_ON_ID_VACANTE FOREIGN KEY (id_vacante) REFERENCES vacantes (id_vacante);

ALTER TABLE requisitos
    ADD CONSTRAINT FK_REQUISITOS_ON_ID_VACANTE FOREIGN KEY (id_vacante) REFERENCES vacantes (id_vacante);

ALTER TABLE ubicaciones
    ADD CONSTRAINT FK_UBICACIONES_ON_ID_PADRE_UBICACION FOREIGN KEY (id_padre_ubicacion) REFERENCES ubicaciones (id_ubicacion);

ALTER TABLE usuarios
    ADD CONSTRAINT FK_USUARIOS_ON_ID_UBICACION FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones (id_ubicacion);

ALTER TABLE usuarios_roles
    ADD CONSTRAINT FK_USUARIOS_ROLES_ON_ID_ROL FOREIGN KEY (id_rol) REFERENCES roles (id_rol);

ALTER TABLE usuarios_roles
    ADD CONSTRAINT FK_USUARIOS_ROLES_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);

ALTER TABLE vacantes
    ADD CONSTRAINT FK_VACANTES_ON_ID_EMPRESA FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa);

ALTER TABLE vacantes
    ADD CONSTRAINT FK_VACANTES_ON_ID_UBICACION FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones (id_ubicacion);

ALTER TABLE vacantes
    ADD CONSTRAINT FK_VACANTES_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario);